package testcases

// Code generated by scripts/gen_test_cases.cjs; DO NOT EDIT.

type TestCase struct {
	Base, WeaponR, WeaponL, Size string
	Mount                          string
	MountScale                     float64
	SeatOffset                     []float64
	ParticlesDensity               *float64
}

var retailCases = []TestCase{
	{Base: "https://www.wowhead.com/wotlk/npc=36855/lady-deathwhisper", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/wotlk/npc=36612/lord-marrowgar", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/npc=71953/xuen", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=154515/yulon", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "https://www.wowhead.com/npc=56439/sha-of-doubt", WeaponR: "", WeaponL: "", Size: "giant"},
	{Base: "https://www.wowhead.com/npc=102672/nythendra", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "https://www.wowhead.com/npc=211664/elisande", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=113201/thicket-manahunter", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=68397/lei-shen", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=114895/nightbane#modelviewer", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "https://www.wowhead.com/mop-classic/npc=64986/heavenly-onyx-cloud-serpent", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "local::creature\\\\protodragonshadowflame\\\\protodragonshadowflame_body", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "local::creature\\\\arcanegolem2voidmount\\\\arcanegolem2voidmount", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "local::spells/arthas_souls_attack", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "local::spells/deathknight_bloodboil", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "local::spells/deathknight_bloodboil_new", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=172613/rokhan", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=187590/merithra", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=176789/lady-liadrin", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=208418/flamecrested-portalweaver", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=187609/earthcaller-yevaa", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=209065/austin-huxworth", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=229161/darkfuse-brute", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=181398/malganis", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=82057/shattered-hand", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=245601/enforcer-jaktull", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=214899/ebyssian", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=3095/fela", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=9448/scarlet-praetorian#modelviewer", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=16867/shattered-hand-grunt", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=37007/deathbound-ward", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/item=87777/reins-of-the-astral-cloud-serpent#modelviewer", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "local::creature\\\\ragnaros2\\\\ragnaros2", WeaponR: "", WeaponL: "", Size: "giant"},
	{Base: "https://www.wowhead.com/object=531961/untethered-xybucha", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?ninja-turtle#fM80z0zN89c8G8ol8u8MPd8I8o28N8kq8A8kI8fo8M1r8rb8MKS8zYh8dAn8Mx4808rr8MPI8fk8M1A8rL8MQg8fV8M1o8fm8M1M8rf8MPj8rw8MPt8ri8MPE8L8ke877ozqXd87czbRH808MTC808zqgi87cwLU87czm5q808zqyd808zqhM808zbgk87MzbSq87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?marauder#fl80z0zN89c8ko86y8V586h8oM86C8oc86Q8om8638fb8M2k8fa8M1O8zY48dTo8MtC808fr8M2w8ff8M2N8fd8M2b8oV8zzV877hSXK8082My8082N38MzG87mSXX808SXQ808SXS8082AM8MzG8SXW8082bB87M2bB87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?red-dh#fm8zb0zN89c858fD8bb8Muh8bl8MNW8qP8MfC8Mtc808bF8MAa8zYA8dAU8X8rG8Z8rX8Y8MIF8bh8MuC848fx818fV8bW8Mpz8br8MuA8bw8Mut8bU8MLa8W8dY8oy8fb838fI8bx8MIS8bn8MIi876H1R8081PB808DHH87sYdM808mjK808muM8083Aj8MzI8083Aj8MzI87V", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?black-dh#fm8zb0zN89c8X8rI8W8dZ8Y8rt8Z8rX8bn8MIi8bx8MIS8bl8MNU8bF8MAs858fD8bU8MLa8qP8MfC818fa8bW8MT28zYA8dAU8bh8MuC8bb8Muf8bw8Mut8br8MuA8Mtc80848fL8oy8fq838MLZ874FKk87VzaUr87kzoyR87c30N808vxh808HPT87MHPT87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?frost-prince#fa80o0zN89c8zZ8jY8z18nw8z28nj8z38n18z48yo8M08yL8Mz8yt8MM8yC8og8yh8sW8z3g8aM8z5P8zYv8dLv8Mtr877inNk808zMaD808zMal808zMaO808zVpW87Vzzei8MIv83MZ8Maz8zVDJ808zMnO8MIv8zoFW87MzoFW87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?samurai-sniper#fz80z0zN89c8a8G8s8z8q8O8b8zc8fh8M2Q8d8zh8fu8M218sc8zya8MEt8wUK8fG8M238k58zdw8zYw8dAG8Mx2877iG4k808G4s87cG4V87VI0p808G4o808G5s808G4R808G51808r5J87s", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?plague-mage#fm80R0zN89c8H8bA8F8q58J8bH8K8MLf8bK8MAt8bO8MAB8O8ds8S8dn8U8dE8bJ8MAy8bC8MA08qO8MfV8zYN8dAO8bQ8MLs8bg8MNr8bv8MNB8MgK8wTB8MtM808on8df8Q8MLQ877MyX4808yYm87cyYM87VyP1808yX2808yPK808yY7MyPW808tAf87MtG7k", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?orc-warrior#fM80m0zN89c8G8ol8u8oV8I8o28N8kq8A8kI8fo8M1r8rb8MKS8zYh8dAn8Mx4808rr8MPI8fk8M1A8rL8MQg8fV8M1o8fm8M1M8rf8MPj8rw8MPt8ri8MPE8L8kg877oyxZ808yx287cytM87VtVQ808ytz808tmw808yx1808tVb808tMM87MtLs87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?tauren-druid#fn80k0zN89c8oO8SD8oK8VHu8oP8SZ8TS8VHE8rX8MWJ8TU8VHD8T18VJb8zYO8dpw8MtL808mf8VJQ8mw8SW8TZ8VJk8T28VJf8T38VJG8j08VJC8jM8VJF8jc8VJU8r18MXm8oQ8S58T48VJt8T58VJE876zRZ7MzRZM808zRZm808zRY387VzRZV808zRY5808zRZc808zRZz808zRY4808zbCP8cBO808zbC58cBO87V", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/npc=149816/prince-erazmin", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/dressing-room?mechagnome-archer#fB80c0zN89c8od8MCv8ob8MCo8or8zMd8of8zMG8ow8zMn8ks8zMv8dF8MBg8zZ08dTr8MtF808oh8zM38ou8zc08dK8MDk877v22P87VqlJ8zLv87mzVq287c", WeaponR: "", WeaponL: "", Size: ""},
}
var classicCases = []TestCase{
	{Base: "https://www.wowhead.com/mop-classic/npc=28714/ildine-sorrowspear", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/npc=28674/aludane-whitecloud", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/npc=30115/vereesa-windrunner", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/npc=32678/emeline-fizzlefry", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/npc=32677/whirt-the-all-knowing", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/wotlk/npc=36612/lord-marrowgar", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/wotlk/npc=36853/sindragosa", WeaponR: "", WeaponL: "", Size: "hero"},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?orc-warrior#fM80m0zN89c8u8VkZ8G8VRs8I8VRh8N8VRp8A8VRe877gyxZ808yx2808zRZm808ytM87VtVQ808ytz808tmw808yx1808tVb808tMM87MtLs87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?plague-mage#fm80R0zN89c8F8Vqp8H8Vqv8J8VqK8K8VqX8O8Vb77eyX4808yYm87cyYM87VyP1808yX2808yPK808yY7MyPW808tAf87MtG7k", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?samurai-sniper#fz80z0zN89c8s8VVX8a8Vom8q8Vow8b8Von8d8VoC877gG4k808G4s87cG4V87VI0p808G4o808G5s808G4R808G51808r5J87s", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?dwarf-archer#fc80z0zN89c8x8Vsy8t8VsU8g8Va08e8Vaq8v8VaI877gfq3808fq187cfqZ87Vfpm808fq4808fsq808fq2808fP5808rWK87s", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?goblin-rogue#fs80m0zN89c8zJ8Vhv8MvI8wl38zO8VhB8MvN8wBL8MvA8wBl877vpOB87cpKv87VpS7MpKl808pUw808pKC808pSY808tAf87MtLi87o", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?troll-warrior#fR80m0zN89c8zg8Vik8ze8ViI8zv8wlE8zE8Vie8zl8ViD877vpOi87cpOG87VpSN808pOu808pUu808pOd808pST808pqS87s", WeaponR: "", WeaponL: "", Size: ""},
	{Base: "https://www.wowhead.com/mop-classic/dressing-room?undead-rogue#fV80m0zN89c868VbW8zz8Vb38zM8Rja8zc8Vdi8zm8Vdj877vdTV87cdxz87VdAJ808dlh808dls808dlT808dLC808fck87MdCt87o", WeaponR: "", WeaponL: "", Size: ""},
}

func RetailCases() []TestCase  { return retailCases }
func ClassicCases() []TestCase { return classicCases }
