//===========================================================================
// 
// Just another Warcraft III map
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: Unknown
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // Generated
    trigger                 gg_trg_Melee_Initialization = null
endglobals

function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = BlzCreateUnitWithSkin( p, 'Hpal', -3163.2, 2378.2, 60.390, 'Hpal' )
    set u = BlzCreateUnitWithSkin( p, 'Hamg', -3231.2, 2414.3, 118.201, 'Hamg' )
    set u = BlzCreateUnitWithSkin( p, 'Hblm', -3057.3, 2360.2, 207.812, 'Hblm' )
    set u = BlzCreateUnitWithSkin( p, 'hmpr', -3143.4, 2270.0, 141.807, 'hmpr' )
    set u = BlzCreateUnitWithSkin( p, 'hsor', -3169.1, 2451.7, 16.845, 'hsor' )
    set u = BlzCreateUnitWithSkin( p, 'odoc', -3156.6, 2598.6, 233.538, 'odoc' )
    set u = BlzCreateUnitWithSkin( p, 'oshm', -2964.5, 2454.4, 181.169, 'oshm' )
    set u = BlzCreateUnitWithSkin( p, 'ospw', -3231.2, 2530.5, 316.731, 'ospw' )
    set u = BlzCreateUnitWithSkin( p, 'okod', -3111.0, 2509.2, 66.635, 'okod' )
    set u = BlzCreateUnitWithSkin( p, 'edot', -3240.5, 2566.5, 327.331, 'edot' )
    set u = BlzCreateUnitWithSkin( p, 'edoc', -3066.0, 2377.0, 355.921, 'edoc' )
    set u = BlzCreateUnitWithSkin( p, 'edry', -3014.1, 2468.6, 183.175, 'edry' )
    set u = BlzCreateUnitWithSkin( p, 'unec', -3279.0, 2561.4, 310.142, 'unec' )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Melee Initialization
//
// Default melee game initialization for all players
//===========================================================================
function Trig_Melee_Initialization_Actions takes nothing returns nothing
    call SetTimeOfDay( 0.00 )
    call SetTimeOfDayScalePercentBJ( 0.00 )
    call BlzShowTerrain( false )
    call CreateFogModifierRectBJ( true, Player(0), FOG_OF_WAR_VISIBLE, GetPlayableMapRect() )
    call PanCameraToTimedLocForPlayer( Player(0), GetRectCenter(GetPlayableMapRect()), 0 )
    call CinematicModeBJ( true, GetPlayersAll() )
    call CinematicFadeBJ( bj_CINEFADETYPE_FADEOUT, 0.00, "ReplaceableTextures\\CameraMasks\\White_mask.blp", 0, 0, 0, 0 )
    call PolledWait( 0.50 )
    call CinematicModeExBJ( false, GetPlayersAll(), 0.50 )
    call CinematicFadeBJ( bj_CINEFADETYPE_FADEIN, 0.00, "ReplaceableTextures\\CameraMasks\\White_mask.blp", 0, 0, 0, 0 )
    call PanCameraToTimedLocForPlayer( Player(0), GetPlayerStartLocationLoc(Player(0)), 0 )
endfunction

//===========================================================================
function InitTrig_Melee_Initialization takes nothing returns nothing
    set gg_trg_Melee_Initialization = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Melee_Initialization(  )
endfunction

//===========================================================================
function RunInitializationTriggers takes nothing returns nothing
    call ConditionalTriggerExecute( gg_trg_Melee_Initialization )
endfunction

//***************************************************************************
//*
//*  Upgrades
//*
//***************************************************************************

function InitUpgrades_Player0 takes nothing returns nothing
    call SetPlayerTechResearched( Player(0), 'Rhme', 3 )
    call SetPlayerTechResearched( Player(0), 'Rhra', 3 )
    call SetPlayerTechResearched( Player(0), 'Rhhb', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhar', 3 )
    call SetPlayerTechResearched( Player(0), 'Rhgb', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhac', 3 )
    call SetPlayerTechResearched( Player(0), 'Rhde', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhpt', 2 )
    call SetPlayerTechResearched( Player(0), 'Rhan', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhst', 2 )
    call SetPlayerTechResearched( Player(0), 'Rhla', 3 )
    call SetPlayerTechResearched( Player(0), 'Rhri', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhlh', 2 )
    call SetPlayerTechResearched( Player(0), 'Rhse', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhfl', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhrt', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhss', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhpm', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhfc', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhfs', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhcd', 1 )
    call SetPlayerTechResearched( Player(0), 'Rhsb', 1 )
    call SetPlayerTechResearched( Player(0), 'Rome', 3 )
    call SetPlayerTechResearched( Player(0), 'Rora', 3 )
    call SetPlayerTechResearched( Player(0), 'Roar', 3 )
    call SetPlayerTechResearched( Player(0), 'Rwdm', 1 )
    call SetPlayerTechResearched( Player(0), 'Ropg', 1 )
    call SetPlayerTechResearched( Player(0), 'Robs', 1 )
    call SetPlayerTechResearched( Player(0), 'Rows', 1 )
    call SetPlayerTechResearched( Player(0), 'Roen', 1 )
    call SetPlayerTechResearched( Player(0), 'Rovs', 1 )
    call SetPlayerTechResearched( Player(0), 'Rowd', 2 )
    call SetPlayerTechResearched( Player(0), 'Rost', 2 )
    call SetPlayerTechResearched( Player(0), 'Rosp', 3 )
    call SetPlayerTechResearched( Player(0), 'Rotr', 1 )
    call SetPlayerTechResearched( Player(0), 'Rolf', 1 )
    call SetPlayerTechResearched( Player(0), 'Rowt', 2 )
    call SetPlayerTechResearched( Player(0), 'Rorb', 1 )
    call SetPlayerTechResearched( Player(0), 'Robk', 1 )
    call SetPlayerTechResearched( Player(0), 'Ropm', 1 )
    call SetPlayerTechResearched( Player(0), 'Robf', 1 )
    call SetPlayerTechResearched( Player(0), 'Resm', 3 )
    call SetPlayerTechResearched( Player(0), 'Resw', 3 )
    call SetPlayerTechResearched( Player(0), 'Rema', 3 )
    call SetPlayerTechResearched( Player(0), 'Rerh', 3 )
    call SetPlayerTechResearched( Player(0), 'Renb', 1 )
    call SetPlayerTechResearched( Player(0), 'Reuv', 1 )
    call SetPlayerTechResearched( Player(0), 'Resc', 1 )
    call SetPlayerTechResearched( Player(0), 'Remg', 1 )
    call SetPlayerTechResearched( Player(0), 'Remk', 1 )
    call SetPlayerTechResearched( Player(0), 'Reib', 1 )
    call SetPlayerTechResearched( Player(0), 'Redt', 2 )
    call SetPlayerTechResearched( Player(0), 'Redc', 2 )
    call SetPlayerTechResearched( Player(0), 'Resi', 1 )
    call SetPlayerTechResearched( Player(0), 'Recb', 1 )
    call SetPlayerTechResearched( Player(0), 'Reht', 1 )
    call SetPlayerTechResearched( Player(0), 'Repb', 1 )
    call SetPlayerTechResearched( Player(0), 'Rers', 1 )
    call SetPlayerTechResearched( Player(0), 'Rehs', 1 )
    call SetPlayerTechResearched( Player(0), 'Reeb', 1 )
    call SetPlayerTechResearched( Player(0), 'Reec', 1 )
    call SetPlayerTechResearched( Player(0), 'Rews', 1 )
    call SetPlayerTechResearched( Player(0), 'Repm', 1 )
endfunction

function InitUpgrades takes nothing returns nothing
    call InitUpgrades_Player0(  )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )

endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call InitUpgrades(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )
    call RunInitializationTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_003" )
    call SetMapDescription( "TRIGSTR_005" )
    call SetPlayers( 1 )
    call SetTeams( 1 )
    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )

    call DefineStartLocation( 0, 960.0, 2688.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )
    call InitGenericPlayerSlots(  )
endfunction

